import pandas as pd

# Create expanded data with 50 examples for Input and Output
expanded_data = {
    "Input": [  "How do I access the library section of EduGainer?",
  "How can I pay the library fee?",
  "What classes can I enroll in at EduGainer?",
  "How can I access the EduGainer homepage?",
  "How do I log in to my EduGainer account?",
  "What is the process to register on the EduGainer website?",
  "What should I do if I forgot my password?",
  "How can I start chatting with the EduGainer assistant?",
  "Where can I find the policies of EduGainer?",
  "What resources are available on the EduGainer platform?",
  "How do I complete the new registration process?",
  "How can I access my dashboard?",
  "How can I view and edit my profile?",
  "Where can I find stationery items on EduGainer?",
  "Who are you?",
              
        "What can you help me with?",
        "Can you assist with library seat reservations?",
        "How do I access my class schedule?",
        "Are you available 24/7?",
        "Can I change my registered email address?",
        "How do I reset my password?",
        "Can you suggest study techniques?",
        "Are you integrated with EduGainer's services?",
        "Can you provide real-time seat availability?",
        "What subjects do you cover?",
        "Can I view my upcoming assignments?",
        "How do I contact support?",
        "Can you help me with mock interviews?",
        "Do you track my progress?",
        "How do I book a group study session?",
        "Can I customize notifications?",
        "Can I request tutoring on a specific topic?",
        "How do I check exam results?",
        "What are your key features?",
        "Tell me about EduGainer.",
        "What is EduGainer's mission?",
        "How does EduGainer support offline education?",
        "What kind of courses does EduGainer offer?",
        "What innovative solutions does EduGainer provide?",
        "How does EduGainer help with exam preparation?",
        "Tell me about Classmate.",
        "Who is the founder of EduGainer?",
        "Where is EduGainer located?",
        "What is EduGainer's primary goal?",
        "How does EduGainer contribute to rural education?",
        "What partnerships does EduGainer have?",
        "How does EduGainer enhance personalized learning?",
        "What age groups does EduGainer cater to?",
        "What technologies does EduGainer utilize?",
        "Does EduGainer offer certification programs?",
        "How does EduGainer engage with local communities?",
        "What feedback have students provided about EduGainer?",
        "Is there a mobile app for EduGainer?",
        "How can I get involved with EduGainer?",
        "Who are you?",
        "What can you help me with?",
        "Can you assist with library seat reservations?",
        "How do I access my class schedule?",
        "Are you available 24/7?",
        "Can I change my registered email address?",
        "How do I reset my password?",
        "Can you suggest study techniques?",
        "Are you integrated with EduGainer's services?",
        "Can you provide real-time seat availability?",
        "What subjects do you cover?",
        "Can I view my upcoming assignments?",
        "How do I contact support?",
        "Can you help me with mock interviews?",
        "Do you track my progress?",
        "How do I book a group study session?",
        "Can I customize notifications?",
        "Can I request tutoring on a specific topic?",
        "How do I check exam results?",
        "What are your key features?",
        "What services does EduGainer's offer?",
        "How can I use EduGainer's for library seat management?",
        "What subjects are covered in EduGainer's coaching classes?",
        "What makes EduGainer's different from other EdTech platforms?",
        "How do I register for a coaching class at EduGainer's?",
        "What benefits do EduGainer's library services provide?",
        "Can I check library seat availability in real-time on EduGainer's?",
        "How does EduGainer's improve exam preparation?",
        "What are the operational hours for EduGainer's library services?",
        "How does EduGainer's coaching help students with exam stress?",
        "What products does MeriStationary offer?",
        "Why choose MeriStationary over other suppliers?",
        "Are MeriStationary products affordable for students?",
        "Does MeriStationary provide discounts on bulk purchases?",
        "How is the quality of MeriStationary products compared to other brands?",
        "Can I buy scientific calculators from MeriStationary?",
        "What kind of notebooks are available at MeriStationary?",
        "Does MeriStationary offer eco-friendly products?",
        "How does MeriStationary ensure product quality?",
        "Can I return products if I'm unsatisfied with my purchase at MeriStationary?",
        "What services does EduGainer's provide?",
        "How can I use EduGainer's to book library seats?",
        "Which subjects are taught in EduGainer's classes?",
        "What sets EduGainer's apart from other platforms?",
        "How do I enroll in a class on EduGainer's?",
        "What advantages do EduGainer's library services offer?",
        "Can I view library seat availability on EduGainer's platform?",
        "How does EduGainer's coaching improve exam readiness?",
        "When are EduGainer's library services available?",
        "How does EduGainer's reduce exam anxiety for students?",
        "What stationery items does MeriStationary sell?",
        "Why should I choose MeriStationary?",
        "Are MeriStationary products student-friendly in price?",
        "Do I get bulk discounts with MeriStationary?",
        "Is the quality of MeriStationary products reliable?",
        "Can I purchase calculators from MeriStationary?",
        "What types of notebooks does MeriStationary stock?",
        "Does MeriStationary prioritize eco-friendly products?",
        "How does MeriStationary guarantee quality?",
        "Can I return items bought from MeriStationary?",
        "What services are included in EduGainer's offering?",
        "How do I manage library bookings on EduGainer's?",
        "Which subjects are covered by EduGainer's teaching?",
        "What makes EduGainer's stand out from competitors?",
        "How do I sign up for classes with EduGainer's?",
        "What are the perks of using EduGainer's library?",
        "Is it possible to check real-time seat availability at EduGainer's?",
        "How does EduGainer's improve academic performance?",
        "What are the working hours of EduGainer's library?",
        "What does EduGainer's coaching do to help with exam stress?",
         "What services does EduGainer's offer?",
        "How can I use EduGainer's for library seat management?",
        "What subjects are covered in EduGainer's coaching classes?",
        "What makes EduGainer's different from other EdTech platforms?",
        "How do I register for a coaching class at EduGainer's?",
        "What benefits do EduGainer's library services provide?",
        "Can I check library seat availability in real-time on EduGainer's?",
        "How does EduGainer's improve exam preparation?",
        "What are the operational hours for EduGainer's library services?",
        "How does EduGainer's coaching help students with exam stress?",
        "What products does MeriStationary offer?",
        "Why choose MeriStationary over other suppliers?",
        "Are MeriStationary products affordable for students?",
        "Does MeriStationary provide discounts on bulk purchases?",
        "How is the quality of MeriStationary products compared to other brands?",
        "Can I buy scientific calculators from MeriStationary?",
        "What kind of notebooks are available at MeriStationary?",
        "Does MeriStationary offer eco-friendly products?",
        "How does MeriStationary ensure product quality?",
        "Can I return products if I'm unsatisfied with my purchase at MeriStationary?",
        "What is EduGainer's cancellation policy?",
        "How do I apply for a MeriStationary bulk discount?",
        "Can EduGainer's coaching help with college entrance exams?",
        "What are the technology features integrated into EduGainer's platform?",
        "Can I book a library seat for a group of people on EduGainer's?",
        "What makes EduGainer's coaching methods effective?",
        "How can I get a demo of EduGainer's platform?",
        "Does MeriStationary sell eco-friendly pens?",
        "Is there a free trial for EduGainer's classes?",
        "What is the refund policy for MeriStationary?",
        "How does EduGainer's provide personalized learning?",
        "Can I purchase MeriStationary products online?",
        "What are the study resources available at EduGainer's library?",
        "How often are classes scheduled at EduGainer's?",
        "Does EduGainer's provide study materials for competitive exams?",
        "Are EduGainer's tutors certified?",
        "How can EduGainer's help me improve my time management?",
        "What is the process for ordering customized notebooks at MeriStationary?",
        "What teaching methods are used in EduGainer's coaching classes?",
        "Does MeriStationary deliver internationally?",
        "How does EduGainer's ensure student success?",
        "Is there a mobile app for EduGainer's services?",
        "What discounts are available for EduGainer's coaching?",
        "Can I book library seats for an entire semester at EduGainer's?",
        "What payment options are accepted on EduGainer's?",
        "How does EduGainer's help students prepare for board exams?",
        "Can I access EduGainer's library digitally?",
        "How do I cancel my MeriStationary order?",
        "Does EduGainer's offer any internship opportunities?",
        "What kind of online tools does EduGainer's provide for exam practice?",
        "How can I contact EduGainer's customer support?",
        "What kind of stationery bundles does MeriStationary offer?",
        "What is the maximum library booking duration on EduGainer's?",
        "How are tutors selected for EduGainer's coaching?",
        "Does MeriStationary offer same-day delivery?",
        "How do I renew my library membership at EduGainer's?",
        "Can I change my class schedule at EduGainer's?",
        "Does MeriStationary have a loyalty program?",
        "How do I know if a seat is reserved at EduGainer's library?",
        "What kind of online assessments does EduGainer's provide?",
        "Does MeriStationary sell art supplies?",
        "How does EduGainer's monitor student progress?",
        "Is there a minimum purchase requirement for free shipping on MeriStationary?",
        "Can I get personalized feedback on assignments from EduGainer's tutors?",
        "What are the perks of using EduGainer's coaching services?",
        "Can I view past exam papers on EduGainer's platform?",
        "What are the shipping options available at MeriStationary?",
        "Does EduGainer's provide counseling services for students?",
        "Can I purchase a membership for EduGainer's library online?",
        "Does MeriStationary have an exchange policy?",
        "How are the exams conducted on EduGainer's?",
        "How do I sign up for notifications on EduGainer's?",
        "What stationery items are included in MeriStationary's student kit?",
        "Can I pay in installments for EduGainer's coaching?",
        "What safety measures are in place at EduGainer's library?",
        "Does MeriStationary offer seasonal promotions?",
        "How do I know if a class is full on EduGainer's?",
        "What type of notebooks are recommended for EduGainer's classes?",
        "Can I track my progress on EduGainer's platform?",
        "What are the security features of EduGainer's platform?",
        "What writing tools does MeriStationary recommend for students?",
        "Does EduGainer's library offer group study areas?",
        "How do I become a tutor at EduGainer's?",
        "Can I use a discount code on MeriStationary?",
        "What type of exams are supported on EduGainer's platform?",
        "How can I upgrade my subscription plan on EduGainer's?",
        "What writing pads are available at MeriStationary?",
        "Can I get tutoring on specific topics at EduGainer's?",
        "What are the return policies at MeriStationary?",
        "How do I access recorded sessions on EduGainer's platform?",
        "Can I donate books to EduGainer's library?",
        "Does EduGainer's coaching include mock interviews?",
        "What study techniques are taught in EduGainer's classes?",
        "How do I sign up for MeriStationary's newsletter?",
        "What type of calculators are sold by MeriStationary?",
        "How can I check my performance on EduGainer's practice tests?",
        "Does MeriStationary sell personalized stationery?",
        "How are online tests graded on EduGainer's platform?",
        "What subjects are available in EduGainer's live classes?",
        "Does MeriStationary offer gift-wrapping services?",
        "How can I apply for financial aid for EduGainer's coaching?",
          "What services does EduGainer's offer?",
        "How can I use EduGainer's for library seat management?",
        "What subjects are covered in EduGainer's coaching classes?",
        "What makes EduGainer's different from other EdTech platforms?",
        "How do I register for a coaching class at EduGainer's?",
        "What benefits do EduGainer's library services provide?",
        "Can I check library seat availability in real-time on EduGainer's?",
        "How does EduGainer's improve exam preparation?",
        "What are the operational hours for EduGainer's library services?",
        "How does EduGainer's coaching help students with exam stress?",
        "What products does MeriStationary offer?",
        "Why choose MeriStationary over other suppliers?",
        "Are MeriStationary products affordable for students?",
        "Does MeriStationary provide discounts on bulk purchases?",
        "How is the quality of MeriStationary products compared to other brands?",
        "Can I buy scientific calculators from MeriStationary?",
        "What kind of notebooks are available at MeriStationary?",
        "Does MeriStationary offer eco-friendly products?",
        "How does MeriStationary ensure product quality?",
        "Can I return products if I'm unsatisfied with my purchase at MeriStationary?",
        "What is EduGainer's cancellation policy?",
        "How do I apply for a MeriStationary bulk discount?",
        "Can EduGainer's coaching help with college entrance exams?",
        "What are the technology features integrated into EduGainer's platform?",
        "Can I book a library seat for a group of people on EduGainer's?",
        "What makes EduGainer's coaching methods effective?",
        "How can I get a demo of EduGainer's platform?",
        "Does MeriStationary sell eco-friendly pens?",
        "Is there a free trial for EduGainer's classes?",
        "What is the refund policy for MeriStationary?",
        "How does EduGainer's provide personalized learning?",
        "Can I purchase MeriStationary products online?",
        "What are the study resources available at EduGainer's library?",
        "How often are classes scheduled at EduGainer's?",
        "Does EduGainer's provide study materials for competitive exams?",
        "Are EduGainer's tutors certified?",
        "How can EduGainer's help me improve my time management?",
        "What is the process for ordering customized notebooks at MeriStationary?",
        "What teaching methods are used in EduGainer's coaching classes?",
        "Does MeriStationary deliver internationally?",
        "How does EduGainer's ensure student success?",
        "Is there a mobile app for EduGainer's services?",
        "What discounts are available for EduGainer's coaching?",
        "Can I book library seats for an entire semester at EduGainer's?",
        "What payment options are accepted on EduGainer's?",
        "How does EduGainer's help students prepare for board exams?",
        "Can I access EduGainer's library digitally?",
        "How do I cancel my MeriStationary order?",
        "Does EduGainer's offer any internship opportunities?",
        "What kind of online tools does EduGainer's provide for exam practice?",
        "How can I contact EduGainer's customer support?",
        "What kind of stationery bundles does MeriStationary offer?",
        "What is the maximum library booking duration on EduGainer's?",
        "How are tutors selected for EduGainer's coaching?",
        "Does MeriStationary offer same-day delivery?",
        "How do I renew my library membership at EduGainer's?",
        "Can I change my class schedule at EduGainer's?",
        "Does MeriStationary have a loyalty program?",
        "How do I know if a seat is reserved at EduGainer's library?",
        "What kind of online assessments does EduGainer's provide?",
        "Does MeriStationary sell art supplies?",
        "How does EduGainer's monitor student progress?",
        "Is there a minimum purchase requirement for free shipping on MeriStationary?",
        "Can I get personalized feedback on assignments from EduGainer's tutors?",
        "What are the perks of using EduGainer's coaching services?",
        "Can I view past exam papers on EduGainer's platform?",
        "What are the shipping options available at MeriStationary?",
        "Does EduGainer's provide counseling services for students?",
        "Can I purchase a membership for EduGainer's library online?",
        "Does MeriStationary have an exchange policy?",
        "How are the exams conducted on EduGainer's?",
        "How do I sign up for notifications on EduGainer's?",
        "What stationery items are included in MeriStationary's student kit?",
        "Can I pay in installments for EduGainer's coaching?",
        "What safety measures are in place at EduGainer's library?",
        "Does MeriStationary offer seasonal promotions?",
        "How do I know if a class is full on EduGainer's?",
        "What type of notebooks are recommended for EduGainer's classes?",
        "Can I track my progress on EduGainer's platform?",
        "What are the security features of EduGainer's platform?",
        "What writing tools does MeriStationary recommend for students?",
        "Does EduGainer's library offer group study areas?",
        "How do I become a tutor at EduGainer's?",
        "Can I use a discount code on MeriStationary?",
        "What type of exams are supported on EduGainer's platform?",
        "How can I upgrade my subscription plan on EduGainer's?",
        "What writing pads are available at MeriStationary?",
        "Can I get tutoring on specific topics at EduGainer's?",
        "What are the return policies at MeriStationary?",
        "How do I access recorded sessions on EduGainer's platform?",
        "Can I donate books to EduGainer's library?",
        "Does EduGainer's coaching include mock interviews?",
        "What study techniques are taught in EduGainer's classes?",
        "How do I sign up for MeriStationary's newsletter?",
        "What type of calculators are sold by MeriStationary?",
        "How can I check my performance on EduGainer's practice tests?",
        "Does MeriStationary sell personalized stationery?",
        "How are online tests graded on EduGainer's platform?",
        "What subjects are available in EduGainer's live classes?",
        "Does MeriStationary offer gift-wrapping services?",
        "How can I apply for financial aid for EduGainer's coaching?",
          "What services does EduGainer's offer?",
        "How can I use EduGainer's for library seat management?",
        "What subjects are covered in EduGainer's coaching classes?",
        "What makes EduGainer's different from other EdTech platforms?",
        "How do I register for a coaching class at EduGainer's?",
        "What benefits do EduGainer's library services provide?",
        "Can I check library seat availability in real-time on EduGainer's?",
        "How does EduGainer's improve exam preparation?",
        "What are the operational hours for EduGainer's library services?",
        "How does EduGainer's coaching help students with exam stress?",
        "What products does MeriStationary offer?",
        "Why choose MeriStationary over other suppliers?",
        "Are MeriStationary products affordable for students?",
        "Does MeriStationary provide discounts on bulk purchases?",
        "How is the quality of MeriStationary products compared to other brands?",
        "Can I buy scientific calculators from MeriStationary?",
        "What kind of notebooks are available at MeriStationary?",
        "Does MeriStationary offer eco-friendly products?",
        "How does MeriStationary ensure product quality?",
        "Can I return products if I'm unsatisfied with my purchase at MeriStationary?",
        "What is EduGainer's cancellation policy?",
        "How do I apply for a MeriStationary bulk discount?",
        "Can EduGainer's coaching help with college entrance exams?",
        "What are the technology features integrated into EduGainer's platform?",
        "Can I book a library seat for a group of people on EduGainer's?",
        "What makes EduGainer's coaching methods effective?",
        "How can I get a demo of EduGainer's platform?",
        "Does MeriStationary sell eco-friendly pens?",
        "Is there a free trial for EduGainer's classes?",
        "What is the refund policy for MeriStationary?",
        "How does EduGainer's provide personalized learning?",
        "Can I purchase MeriStationary products online?",
        "What are the study resources available at EduGainer's library?",
        "How often are classes scheduled at EduGainer's?",
        "Does EduGainer's provide study materials for competitive exams?",
        "Are EduGainer's tutors certified?",
        "How can EduGainer's help me improve my time management?",
        "What is the process for ordering customized notebooks at MeriStationary?",
        "What teaching methods are used in EduGainer's coaching classes?",
        "Does MeriStationary deliver internationally?",
        "How does EduGainer's ensure student success?",
        "Is there a mobile app for EduGainer's services?",
        "What discounts are available for EduGainer's coaching?",
        "Can I book library seats for an entire semester at EduGainer's?",
        "What payment options are accepted on EduGainer's?",
        "How does EduGainer's help students prepare for board exams?",
        "Can I access EduGainer's library digitally?",
        "How do I cancel my MeriStationary order?",
        "Does EduGainer's offer any internship opportunities?",
        "What kind of online tools does EduGainer's provide for exam practice?",
        "How can I contact EduGainer's customer support?",
        "What kind of stationery bundles does MeriStationary offer?",
        "What is the maximum library booking duration on EduGainer's?",
        "How are tutors selected for EduGainer's coaching?",
        "Does MeriStationary offer same-day delivery?",
        "How do I renew my library membership at EduGainer's?",
        "Can I change my class schedule at EduGainer's?",
        "Does MeriStationary have a loyalty program?",
        "How do I know if a seat is reserved at EduGainer's library?",
        "What kind of online assessments does EduGainer's provide?",
        "Does MeriStationary sell art supplies?",
        "How does EduGainer's monitor student progress?",
        "Is there a minimum purchase requirement for free shipping on MeriStationary?",
        "Can I get personalized feedback on assignments from EduGainer's tutors?",
        "What are the perks of using EduGainer's coaching services?",
        "Can I view past exam papers on EduGainer's platform?",
        "What are the shipping options available at MeriStationary?",
        "Does EduGainer's provide counseling services for students?",
        "Can I purchase a membership for EduGainer's library online?",
        "Does MeriStationary have an exchange policy?",
        "How are the exams conducted on EduGainer's?",
        "How do I sign up for notifications on EduGainer's?",
        "What stationery items are included in MeriStationary's student kit?",
        "Can I pay in installments for EduGainer's coaching?",
        "What safety measures are in place at EduGainer's library?",
        "Does MeriStationary offer seasonal promotions?",
        "How do I know if a class is full on EduGainer's?",
        "What type of notebooks are recommended for EduGainer's classes?",
        "Can I track my progress on EduGainer's platform?",
        "What are the security features of EduGainer's platform?",
        "What writing tools does MeriStationary recommend for students?",
        "Does EduGainer's library offer group study areas?",
        "How do I become a tutor at EduGainer's?",
        "Can I use a discount code on MeriStationary?",
        "What type of exams are supported on EduGainer's platform?",
        "How can I upgrade my subscription plan on EduGainer's?",
        "What writing pads are available at MeriStationary?",
        "Can I get tutoring on specific topics at EduGainer's?",
        "What are the return policies at MeriStationary?",
        "How do I access recorded sessions on EduGainer's platform?",
        "Can I donate books to EduGainer's library?",
        "Does EduGainer's coaching include mock interviews?",
        "What study techniques are taught in EduGainer's classes?",
        "How do I sign up for MeriStationary's newsletter?",
        "What type of calculators are sold by MeriStationary?",
        "How can I check my performance on EduGainer's practice tests?",
        "Does MeriStationary sell personalized stationery?",
        "How are online tests graded on EduGainer's platform?",
        "What subjects are available in EduGainer's live classes?",
        "Does MeriStationary offer gift-wrapping services?",
        "How can I apply for financial aid for EduGainer's coaching?"
    ],
    "Output": [      "You can access the library section of EduGainer by visiting [this link](https://edugainers.com/library).",
  "To pay the library fee, go to [this page](https://edugainers.com/library/fee-pay).",
  "You can find the available classes by visiting [this link](https://edugainers.com/classes).",
  "You can access the EduGainer homepage by clicking [here](https://edugainers.com/).",
  "To log in to your EduGainer account, visit [this link](https://edugainers.com/login).",
  "You can register on the EduGainer website by following the steps outlined [here](https://edugainers.com/register).",
  "If you've forgotten your password, you can reset it by clicking [here](https://edugainers.com/forgot-password).",
  "To start chatting with the EduGainer assistant, visit [this page](https://edugainers.com/chat/home).",
  "You can find the policies of EduGainer by visiting [this link](https://edugainers.com/Policies).",
  "You can find available resources on EduGainer by visiting [this page](https://edugainers.com/resources).",
  "To complete the new registration process, click [here](https://edugainers.com/new-reg).",
  "You can access your dashboard by visiting [this link](https://edugainers.com/dashboard/:id). Replace :id with your actual user ID.",
  "To view and edit your profile, visit [this page](https://edugainers.com/profile/:id). Replace :id with your actual user ID.",
  "You can find stationery items by visiting [this link](https://edugainers.com/stationary/home).","I am Classmate, developed by EduGainer's team to assist you with your learning and library management needs.",
        "I can help with library seat reservations, coaching class schedules, real-time updates, study techniques, and much more.",
        "Yes, I can assist with real-time library seat reservations on EduGainer's platform.",
        "You can access your class schedule through your EduGainer's account or ask me for a quick overview.",
        "Yes, I'm here 24/7 to assist you with any queries you have related to EduGainer's services.",
        "Yes, you can change your registered email address by updating your profile in your EduGainer's account settings.",
        "To reset your password, click on 'Forgot Password' at the login screen or I can guide you through the process.",
        "Yes, I can suggest effective study techniques like spaced repetition, active recall, and time management tips.",
        "Yes, I am fully integrated with EduGainer's services, including library management, coaching, and more.",
        "Yes, I provide real-time seat availability using EduGainer's system to show you which seats are vacant.",
        "I cover subjects like mathematics, physics, chemistry, biology, and more to help students succeed academically.",
        "You can view your upcoming assignments in your EduGainer's dashboard or by asking me for a summary.",
        "You can contact support by emailing or calling the helpline, or let me know if you need assistance with anything.",
        "Yes, I can help with mock interview practice to prepare you for job or college applications.",
        "Yes, I track your progress through EduGainer's platform, offering insights into your performance.",
        "To book a group study session, visit the library management section or ask me to help you with the process.",
        "Yes, you can customize notifications from your profile settings or ask me to turn on specific alerts for you.",
        "Yes, you can request topic-specific tutoring sessions through EduGainer's platform or by asking me to assist.",
        "You can check your exam results by logging into EduGainer's platform or asking me for a quick update.",
        "My key features include real-time library management, coaching support, personalized study techniques, and progress tracking.",
        "EduGainer is based in Uttarkashi, Uttarakhand, a region known for its natural beauty and educational initiatives.",
        "EduGainer aims to make quality education accessible to students across India, especially in rural areas.",
        "EduGainer's offline presence includes partnerships with local schools and educational institutions in Uttarkashi.",
        "EduGainer offers courses ranging from basic education to advanced technology skills.",
        "EduGainer specializes in creating custom AI-powered solutions for educational purposes.",
        "I provide support for exam preparation, competitive tests, and certification courses.",
        "EduGainer has an AI assistant named 'Classmate,' designed to help students with queries and personalized study plans.",
        "The founder of EduGainer is Shekher Pant, who envisioned this platform to empower students in remote areas.",
        "EduGainer is located in Uttarkashi, Uttarakhand.",
        "EduGainer's primary goal is to bridge the educational gap in remote regions of India.",
        "EduGainer actively contributes to rural education through partnerships and initiatives that promote learning.",
        "EduGainer has partnerships with local schools and educational institutions to enhance educational offerings.",
        "EduGainer utilizes AI-driven tools to provide personalized learning experiences tailored to individual needs.",
        "EduGainer caters to students of all age groups, from primary to higher education.",
        "EduGainer uses various technologies, including AI, online learning platforms, and interactive modules.",
        "Yes, EduGainer offers certification programs in various subjects to help students enhance their qualifications.",
        "EduGainer engages with local communities through workshops, seminars, and collaborative educational projects.",
        "Students have provided positive feedback about EduGainer's personalized approach and effective learning methods.",
        "Yes, EduGainer has a mobile app for convenient access to learning materials and resources.",
        "You can get involved with EduGainer by volunteering, participating in programs, or collaborating on projects.",  "I am Classmate, developed by EduGainer's team to assist you with your learning and library management needs.",
        "I can help with library seat reservations, coaching class schedules, real-time updates, study techniques, and much more.",
        "Yes, I can assist with real-time library seat reservations on EduGainer's platform.",
        "You can access your class schedule through your EduGainer's account or ask me for a quick overview.",
        "Yes, I'm here 24/7 to assist you with any queries you have related to EduGainer's services.",
        "Yes, you can change your registered email address by updating your profile in your EduGainer's account settings.",
        "To reset your password, click on 'Forgot Password' at the login screen or I can guide you through the process.",
        "Yes, I can suggest effective study techniques like spaced repetition, active recall, and time management tips.",
        "Yes, I am fully integrated with EduGainer's services, including library management, coaching, and more.",
        "Yes, I provide real-time seat availability using EduGainer's system to show you which seats are vacant.",
        "I cover subjects like mathematics, physics, chemistry, biology, and more to help students succeed academically.",
        "You can view your upcoming assignments in your EduGainer's dashboard or by asking me for a summary.",
        "You can contact support by emailing or calling the helpline, or let me know if you need assistance with anything.",
        "Yes, I can help with mock interview practice to prepare you for job or college applications.",
        "Yes, I track your progress through EduGainer's platform, offering insights into your performance.",
        "To book a group study session, visit the library management section or ask me to help you with the process.",
        "Yes, you can customize notifications from your profile settings or ask me to turn on specific alerts for you.",
        "Yes, you can request topic-specific tutoring sessions through EduGainer's platform or by asking me to assist.",
        "You can check your exam results by logging into EduGainer's platform or asking me for a quick update.",
        "My key features include real-time library management, coaching support, personalized study techniques, and progress tracking.",
        "EduGainer's provides library coaching classes, real-time library seat data, and affordable stationery services through MeriStationary.",
        "EduGainer's allows you to manage library seat bookings in real-time using WebSockets, letting you view and reserve seats easily.",
        "EduGainer's offers coaching in physics, chemistry, mathematics, and other subjects to help students succeed academically.",
        "EduGainer's integrates real-time library management, coaching classes, and affordable stationery services into one comprehensive platform.",
        "You can register for a coaching class by signing up on EduGainer's platform and selecting your preferred subject and time slot.",
        "EduGainer's library services allow real-time seat tracking, convenient booking, and extended hours to ensure productive study sessions.",
        "Yes, EduGainer's provides real-time seat availability using socket.io, allowing students to see vacant spots instantly.",
        "EduGainer's coaching classes use personalized approaches and expert teachers to prepare students thoroughly for their exams.",
        "EduGainer's library services operate from 8 AM to 10 PM, providing students with a comfortable place to study and access resources.",
        "EduGainer's coaching helps alleviate exam stress by offering structured study plans and time management tips tailored to each student.",
        "MeriStationary offers high-quality stationery products, including notebooks, pens, calculators, and other essential supplies.",
        "MeriStationary stands out for its combination of affordability, quality, and a student-focused approach, providing reliable supplies for all.",
        "Yes, MeriStationary ensures affordability for students by offering competitive pricing across all its products.",
        "Yes, MeriStationary provides discounts for bulk purchases, making it ideal for schools and student groups.",
        "MeriStationary provides high-quality products, ensuring durability and reliability, rivaling other popular stationery brands.",
        "Yes, MeriStationary offers scientific calculators along with other study-related tools like geometry sets and rulers.",
        "MeriStationary provides a range of notebooks, including spiral-bound, ruled, and unruled options to suit different needs.",
        "Yes, MeriStationary is committed to sustainability and offers eco-friendly notebooks and paper products.",
        "MeriStationary follows strict quality control standards, ensuring that every product meets the required benchmarks before reaching customers.",
        "Yes, MeriStationary has a hassle-free return policy for products that do not meet customer expectations.",
        "EduGainer's provides a range of services including coaching classes, library seat booking, and real-time seat availability tracking.",
        "You can book library seats through EduGainer's web or mobile app with a simple seat reservation feature.",
        "EduGainer's teaches a variety of subjects such as science, technology, engineering, and mathematics (STEM).",
        "EduGainer's differentiates itself by combining top-tier teaching with advanced technological solutions for better learning outcomes.",
        "Enrollment in EduGainer's coaching classes is easy, just create an account, browse available courses, and select your slot.",
        "EduGainer's library services offer benefits like extended study hours, quiet environments, and personalized seat tracking features.",
        "Yes, students can see available library seats in real-time through EduGainer's intuitive interface for better seat management.",
        "EduGainer's coaching combines personalized feedback and structured learning paths to make exam preparation more effective.",
        "EduGainer's library services are available every day from early morning to late evening, ensuring flexible study times.",
        "By providing a stress-free environment and offering counseling services, EduGainer's helps students overcome exam-related stress.",
        "MeriStationary sells a variety of essential supplies including pens, notebooks, calculators, and other school materials.",
        "MeriStationary is ideal for students due to its competitive prices, high product quality, and focus on student needs.",
        "Yes, MeriStationary has products designed to be student-budget friendly while maintaining excellent quality.",
        "Bulk discounts are available on MeriStationary's platform, especially for institutional orders and large student groups.",
        "MeriStationary guarantees high quality by sourcing products from trusted suppliers and conducting strict quality checks.",
        "Yes, MeriStationary offers calculators, including scientific and basic models, for academic purposes.",
        "A wide variety of notebooks such as hardbound, softbound, ruled, and unruled options are available at MeriStationary.",
        "MeriStationary places importance on sustainability by offering eco-friendly products, including recycled paper notebooks.",
        "MeriStationary's quality assurance processes ensure that all products meet high standards before they are sold.",
        "Yes, MeriStationary offers easy returns on unsatisfactory items with a full refund or exchange option.",
        "EduGainer's provides online and offline coaching, an advanced library management system, and integrated student resources.",
        "Managing library bookings on EduGainer's platform is simple with the easy-to-use booking dashboard.",
        "EduGainer's classes cover subjects like biology, chemistry, physics, and mathematics for students in all levels.",
        "EduGainer's competitive edge lies in its combination of cutting-edge technology and expert tutors for personalized learning.",
        "To sign up for EduGainer's classes, create an account, browse available subjects, and book your preferred time slot.",
        "Using EduGainer's library services gives students access to dedicated study spaces, updated resources, and quiet zones.",
        "Yes, EduGainer's allows students to check real-time seat availability and make bookings instantly through the platform.",
        "EduGainer's coaching services help improve academic performance by offering personalized study schedules and focused feedback.",
        "EduGainer's library operates from 7 AM to 11 PM, providing long study hours for students' convenience.",
        "EduGainer's coaching helps with exam stress by offering personalized learning plans, reducing pressure, and boosting confidence.",
          "EduGainer's provides library coaching classes, real-time library seat data, and affordable stationery services through MeriStationary.",
        "EduGainer's allows you to manage library seat bookings in real-time using WebSockets, letting you view and reserve seats easily.",
        "EduGainer's offers coaching in physics, chemistry, mathematics, and other subjects to help students succeed academically.",
        "EduGainer's integrates real-time library management, coaching classes, and affordable stationery services into one comprehensive platform.",
        "You can register for a coaching class by signing up on EduGainer's platform and selecting your preferred subject and time slot.",
        "EduGainer's library services allow real-time seat tracking, convenient booking, and extended hours to ensure productive study sessions.",
        "Yes, EduGainer's provides real-time seat availability using socket.io, allowing students to see vacant spots instantly.",
        "EduGainer's coaching classes use personalized approaches and expert teachers to prepare students thoroughly for their exams.",
        "EduGainer's library services operate from 8 AM to 10 PM, providing students with a comfortable place to study and access resources.",
        "EduGainer's coaching helps alleviate exam stress by offering structured study plans and time management tips tailored to each student.",
        "MeriStationary offers high-quality stationery products, including notebooks, pens, calculators, and other essential supplies.",
        "MeriStationary stands out for its combination of affordability, quality, and a student-focused approach, providing reliable supplies for all.",
        "Yes, MeriStationary ensures affordability for students by offering competitive pricing across all its products.",
        "Yes, MeriStationary provides discounts for bulk purchases, making it ideal for schools and student groups.",
        "MeriStationary provides high-quality products, ensuring durability and reliability, rivaling other popular stationery brands.",
        "Yes, MeriStationary offers scientific calculators along with other study-related tools like geometry sets and rulers.",
        "MeriStationary provides a range of notebooks, including spiral-bound, ruled, and unruled options to suit different needs.",
        "Yes, MeriStationary is committed to sustainability and offers eco-friendly notebooks and paper products.",
        "MeriStationary follows strict quality control standards, ensuring that every product meets the required benchmarks before reaching customers.",
        "Yes, MeriStationary has a hassle-free return policy for products that do not meet customer expectations.",
        "EduGainer's coaching classes can be canceled with a full refund up to 48 hours before the start of the course.",
        "To apply for a bulk discount at MeriStationary, you need to contact customer support with your order details.",
        "Yes, EduGainer's coaching provides special programs to prepare students for college entrance exams such as JEE and NEET.",
        "EduGainer's platform features advanced tools like real-time seat booking, AI-based performance tracking, and interactive study materials.",
        "Yes, you can book library seats for a group of students through EduGainer's seat management tool on the platform.",
        "EduGainer's coaching methods emphasize interactive learning, personalized feedback, and flexible study schedules.",
        "You can request a demo of EduGainer's platform by contacting customer support or filling out the demo request form on the website.",
        "Yes, MeriStationary offers eco-friendly pens made from recycled materials and sustainable packaging.",
        "Yes, EduGainer's provides a one-week free trial for its coaching classes, allowing students to experience the platform.",
        "MeriStationary offers a full refund for unused and undamaged products returned within 14 days of purchase.",
        "EduGainer's delivers personalized learning through AI algorithms that adapt study plans based on each student's performance.",
        "Yes, MeriStationary allows online purchases and delivers products directly to your doorstep with various shipping options.",
        "EduGainer's library offers textbooks, reference materials, previous exam papers, and online resources for comprehensive study support.",
        "EduGainer's coaching classes are scheduled throughout the week, with flexible timings to accommodate students' different schedules.",
        "Yes, EduGainer's provides specially curated study materials designed to help students prepare effectively for competitive exams.",
        "All EduGainer's tutors are certified professionals with years of experience in their respective fields of expertise.",
        "EduGainer's teaches time management techniques, helping students balance study time and other activities efficiently.",
        "To order customized notebooks at MeriStationary, fill out the customization form on the website and specify your preferences.",
        "EduGainer's uses a variety of teaching methods including interactive videos, practice tests, and group discussions to engage students.",
        "Yes, MeriStationary provides international shipping for its products, with additional fees based on the destination country.",
        "EduGainer's ensures student success through personalized feedback, continuous assessments, and expert guidance from tutors.",
        "Yes, EduGainer's has a mobile app available on both Android and iOS, allowing students to access all services on the go.",
        "EduGainer's offers discounts for early sign-ups, group enrollments, and annual subscriptions, providing cost-effective options for students.",
        "Yes, EduGainer's allows long-term library seat bookings, letting students reserve their preferred seats for an entire semester.",
        "EduGainer's accepts payments through credit cards, debit cards, UPI, net banking, and other secure online payment methods.",
        "EduGainer's helps students prepare for board exams by offering targeted study plans, mock exams, and subject-specific coaching.",
        "Yes, EduGainer's offers digital access to its library, where students can browse e-books, online journals, and research papers.",
        "You can cancel your MeriStationary order by logging into your account and selecting the cancel option under order details.",
        "Yes, EduGainer's offers internship opportunities in various departments including content creation, marketing, and operations.",
        "EduGainer's provides online tools such as timed practice exams, detailed feedback, and AI-driven analysis of student performance.",
        "You can contact EduGainer's customer support through the chat feature on the website, email, or by calling the helpline.",
        "MeriStationary offers pre-assembled stationery bundles tailored for students, including notebooks, pens, calculators, and geometry sets.",
        "EduGainer's library seat booking allows a maximum duration of 12 hours per day for each reservation.",
        "EduGainer's tutors undergo a rigorous selection process, ensuring that only highly qualified and experienced individuals are selected.",
        "Yes, MeriStationary offers same-day delivery in select cities for orders placed before noon.",
        "You can renew your library membership on EduGainer's by logging into your account and selecting the renew membership option.",
        "Yes, EduGainer's allows you to change your class schedule by contacting your tutor and selecting an available time slot.",
        "MeriStationary offers a loyalty program where customers can earn points on purchases and redeem them for discounts.",
        "You can see if a seat is reserved in EduGainer's library by checking the seat's status on the platform's seat management tool.",
        "EduGainer's offers online assessments in multiple formats including timed tests, subject-specific quizzes, and comprehensive exams.",
        "Yes, MeriStationary sells a wide variety of art supplies including sketchbooks, colored pencils, and painting materials.",
        "EduGainer's monitors student progress through regular assessments, performance tracking, and periodic feedback sessions.",
        "Yes, MeriStationary offers free shipping on orders above a certain threshold, usually above ₹500.",
        "EduGainer's tutors provide personalized feedback on student assignments, helping them improve their performance continuously.",
        "EduGainer's coaching services offer personalized study plans, expert tutors, and flexible class schedules to help students excel.",
        "Yes, EduGainer's platform provides access to past exam papers from various boards and competitive exams for student practice.",
        "MeriStationary provides standard, express, and same-day shipping options depending on the location and order size.",
        "Yes, EduGainer's offers counseling services for students needing help with career guidance and personal development.",
        "Yes, you can purchase an EduGainer's library membership online by selecting the membership plan and completing the payment process.",
        "Yes, MeriStationary allows customers to exchange products if they receive the wrong item or if it arrives damaged.",
        "EduGainer's conducts exams online using a secure proctoring system, ensuring a fair testing environment for all students.",
        "You can sign up for notifications on EduGainer's platform by going to your profile settings and enabling email or SMS alerts.",
        "MeriStationary's student kit includes notebooks, pens, rulers, erasers, geometry sets, and a scientific calculator.",
        "Yes, EduGainer's offers an installment payment plan for its coaching services, allowing students to pay in flexible monthly installments.",
        "EduGainer's library is equipped with CCTV cameras, fire safety systems, and staff trained in emergency response procedures.",
        "Yes, MeriStationary offers seasonal promotions, especially around the start of the academic year and festive seasons.",
        "EduGainer's displays class availability in real-time on its platform, ensuring students know if a class is full before enrolling.",
        "EduGainer's recommends spiral-bound or A4-sized notebooks for most of its coaching classes, ensuring ample space for notes.",
        "EduGainer's platform provides a detailed performance dashboard where students can track their progress over time.",
        "EduGainer's platform includes secure login features, encrypted data storage, and compliance with industry-standard safety protocols.",
        "MeriStationary recommends ergonomic pens and pencils designed for comfortable writing during long study sessions.",
        "Yes, EduGainer's library offers group study rooms that can be booked for collaborative sessions or group projects.",
        "To become a tutor at EduGainer's, apply through the careers section of the website, and your application will be reviewed by the team.",
        "Yes, MeriStationary allows the use of discount codes during checkout for additional savings on purchases.",
        "EduGainer's supports various types of exams including multiple-choice tests, essay-based exams, and oral assessments.",
        "You can upgrade your EduGainer's subscription plan by logging into your account and selecting the upgrade option under subscriptions.",
        "MeriStationary offers a range of writing pads including spiral, perforated, and legal pads for various writing needs.",
        "Yes, EduGainer's provides topic-specific tutoring, allowing students to focus on areas they need the most help with.",
        "MeriStationary offers a 14-day return policy for most products, allowing customers to return or exchange items within that period.",
        "Recorded sessions on EduGainer's platform can be accessed by logging into your account and navigating to the class recordings section.",
        "Yes, EduGainer's library accepts book donations, and these contributions are made available to other students in need.",
        "Yes, EduGainer's coaching includes mock interviews for students preparing for college or job applications.",
        "EduGainer's teaches study techniques like time management, active recall, and spaced repetition to enhance learning efficiency.",
        "You can sign up for MeriStationary's newsletter by entering your email on their website to receive updates and offers.",
        "MeriStationary sells both basic and scientific calculators to suit students' various academic needs.",
        "You can check your performance on EduGainer's practice tests by accessing the performance analytics section on your dashboard.",
        "Yes, MeriStationary offers personalized stationery including custom notebooks, pens, and desk organizers.",
        "EduGainer's platform grades online tests using automated systems that provide immediate feedback and score analysis.",
        "EduGainer's live classes cover subjects like mathematics, physics, chemistry, biology, and more for students preparing for exams.",
        "Yes, MeriStationary offers gift-wrapping services for special occasions and during the holiday season.",
        "You can apply for financial aid for EduGainer's coaching by filling out the financial assistance form available on the platform.",
          "EduGainer's provides library coaching classes, real-time library seat data, and affordable stationery services through MeriStationary.",
        "EduGainer's allows you to manage library seat bookings in real-time using WebSockets, letting you view and reserve seats easily.",
        "EduGainer's offers coaching in physics, chemistry, mathematics, and other subjects to help students succeed academically.",
        "EduGainer's integrates real-time library management, coaching classes, and affordable stationery services into one comprehensive platform.",
        "You can register for a coaching class by signing up on EduGainer's platform and selecting your preferred subject and time slot.",
        "EduGainer's library services allow real-time seat tracking, convenient booking, and extended hours to ensure productive study sessions.",
        "Yes, EduGainer's provides real-time seat availability using socket.io, allowing students to see vacant spots instantly.",
        "EduGainer's coaching classes use personalized approaches and expert teachers to prepare students thoroughly for their exams.",
        "EduGainer's library services operate from 8 AM to 10 PM, providing students with a comfortable place to study and access resources.",
        "EduGainer's coaching helps alleviate exam stress by offering structured study plans and time management tips tailored to each student.",
        "MeriStationary offers high-quality stationery products, including notebooks, pens, calculators, and other essential supplies.",
        "MeriStationary stands out for its combination of affordability, quality, and a student-focused approach, providing reliable supplies for all.",
        "Yes, MeriStationary ensures affordability for students by offering competitive pricing across all its products.",
        "Yes, MeriStationary provides discounts for bulk purchases, making it ideal for schools and student groups.",
        "MeriStationary provides high-quality products, ensuring durability and reliability, rivaling other popular stationery brands.",
        "Yes, MeriStationary offers scientific calculators along with other study-related tools like geometry sets and rulers.",
        "MeriStationary provides a range of notebooks, including spiral-bound, ruled, and unruled options to suit different needs.",
        "Yes, MeriStationary is committed to sustainability and offers eco-friendly notebooks and paper products.",
        "MeriStationary follows strict quality control standards, ensuring that every product meets the required benchmarks before reaching customers.",
        "Yes, MeriStationary has a hassle-free return policy for products that do not meet customer expectations.",
        "EduGainer's coaching classes can be canceled with a full refund up to 48 hours before the start of the course.",
        "To apply for a bulk discount at MeriStationary, you need to contact customer support with your order details.",
        "Yes, EduGainer's coaching provides special programs to prepare students for college entrance exams such as JEE and NEET.",
        "EduGainer's platform features advanced tools like real-time seat booking, AI-based performance tracking, and interactive study materials.",
        "Yes, you can book library seats for a group of students through EduGainer's seat management tool on the platform.",
        "EduGainer's coaching methods emphasize interactive learning, personalized feedback, and flexible study schedules.",
        "You can request a demo of EduGainer's platform by contacting customer support or filling out the demo request form on the website.",
        "Yes, MeriStationary offers eco-friendly pens made from recycled materials and sustainable packaging.",
        "Yes, EduGainer's provides a one-week free trial for its coaching classes, allowing students to experience the platform.",
        "MeriStationary offers a full refund for unused and undamaged products returned within 14 days of purchase.",
        "EduGainer's delivers personalized learning through AI algorithms that adapt study plans based on each student's performance.",
        "Yes, MeriStationary allows online purchases and delivers products directly to your doorstep with various shipping options.",
        "EduGainer's library offers textbooks, reference materials, previous exam papers, and online resources for comprehensive study support.",
        "EduGainer's coaching classes are scheduled throughout the week, with flexible timings to accommodate students' different schedules.",
        "Yes, EduGainer's provides specially curated study materials designed to help students prepare effectively for competitive exams.",
        "All EduGainer's tutors are certified professionals with years of experience in their respective fields of expertise.",
        "EduGainer's teaches time management techniques, helping students balance study time and other activities efficiently.",
        "To order customized notebooks at MeriStationary, fill out the customization form on the website and specify your preferences.",
        "EduGainer's uses a variety of teaching methods including interactive videos, practice tests, and group discussions to engage students.",
        "Yes, MeriStationary provides international shipping for its products, with additional fees based on the destination country.",
        "EduGainer's ensures student success through personalized feedback, continuous assessments, and expert guidance from tutors.",
        "Yes, EduGainer's has a mobile app available on both Android and iOS, allowing students to access all services on the go.",
        "EduGainer's offers discounts for early sign-ups, group enrollments, and annual subscriptions, providing cost-effective options for students.",
        "Yes, EduGainer's allows long-term library seat bookings, letting students reserve their preferred seats for an entire semester.",
        "EduGainer's accepts payments through credit cards, debit cards, UPI, net banking, and other secure online payment methods.",
        "EduGainer's helps students prepare for board exams by offering targeted study plans, mock exams, and subject-specific coaching.",
        "Yes, EduGainer's offers digital access to its library, where students can browse e-books, online journals, and research papers.",
        "You can cancel your MeriStationary order by logging into your account and selecting the cancel option under order details.",
        "Yes, EduGainer's offers internship opportunities in various departments including content creation, marketing, and operations.",
        "EduGainer's provides online tools such as timed practice exams, detailed feedback, and AI-driven analysis of student performance.",
        "You can contact EduGainer's customer support through the chat feature on the website, email, or by calling the helpline.",
        "MeriStationary offers pre-assembled stationery bundles tailored for students, including notebooks, pens, calculators, and geometry sets.",
        "EduGainer's library seat booking allows a maximum duration of 12 hours per day for each reservation.",
        "EduGainer's tutors undergo a rigorous selection process, ensuring that only highly qualified and experienced individuals are selected.",
        "Yes, MeriStationary offers same-day delivery in select cities for orders placed before noon.",
        "You can renew your library membership on EduGainer's by logging into your account and selecting the renew membership option.",
        "Yes, EduGainer's allows you to change your class schedule by contacting your tutor and selecting an available time slot.",
        "MeriStationary offers a loyalty program where customers can earn points on purchases and redeem them for discounts.",
        "You can see if a seat is reserved in EduGainer's library by checking the seat's status on the platform's seat management tool.",
        "EduGainer's offers online assessments in multiple formats including timed tests, subject-specific quizzes, and comprehensive exams.",
        "Yes, MeriStationary sells a wide variety of art supplies including sketchbooks, colored pencils, and painting materials.",
        "EduGainer's monitors student progress through regular assessments, performance tracking, and periodic feedback sessions.",
        "Yes, MeriStationary offers free shipping on orders above a certain threshold, usually above ₹500.",
        "EduGainer's tutors provide personalized feedback on student assignments, helping them improve their performance continuously.",
        "EduGainer's coaching services offer personalized study plans, expert tutors, and flexible class schedules to help students excel.",
        "Yes, EduGainer's platform provides access to past exam papers from various boards and competitive exams for student practice.",
        "MeriStationary provides standard, express, and same-day shipping options depending on the location and order size.",
        "Yes, EduGainer's offers counseling services for students needing help with career guidance and personal development.",
        "Yes, you can purchase an EduGainer's library membership online by selecting the membership plan and completing the payment process.",
        "Yes, MeriStationary allows customers to exchange products if they receive the wrong item or if it arrives damaged.",
        "EduGainer's conducts exams online using a secure proctoring system, ensuring a fair testing environment for all students.",
        "You can sign up for notifications on EduGainer's platform by going to your profile settings and enabling email or SMS alerts.",
        "MeriStationary's student kit includes notebooks, pens, rulers, erasers, geometry sets, and a scientific calculator.",
        "Yes, EduGainer's offers an installment payment plan for its coaching services, allowing students to pay in flexible monthly installments.",
        "EduGainer's library is equipped with CCTV cameras, fire safety systems, and staff trained in emergency response procedures.",
        "Yes, MeriStationary offers seasonal promotions, especially around the start of the academic year and festive seasons.",
        "EduGainer's displays class availability in real-time on its platform, ensuring students know if a class is full before enrolling.",
        "EduGainer's recommends spiral-bound or A4-sized notebooks for most of its coaching classes, ensuring ample space for notes.",
        "EduGainer's platform provides a detailed performance dashboard where students can track their progress over time.",
        "EduGainer's platform includes secure login features, encrypted data storage, and compliance with industry-standard safety protocols.",
        "MeriStationary recommends ergonomic pens and pencils designed for comfortable writing during long study sessions.",
        "Yes, EduGainer's library offers group study rooms that can be booked for collaborative sessions or group projects.",
        "To become a tutor at EduGainer's, apply through the careers section of the website, and your application will be reviewed by the team.",
        "Yes, MeriStationary allows the use of discount codes during checkout for additional savings on purchases.",
        "EduGainer's supports various types of exams including multiple-choice tests, essay-based exams, and oral assessments.",
        "You can upgrade your EduGainer's subscription plan by logging into your account and selecting the upgrade option under subscriptions.",
        "MeriStationary offers a range of writing pads including spiral, perforated, and legal pads for various writing needs.",
        "Yes, EduGainer's provides topic-specific tutoring, allowing students to focus on areas they need the most help with.",
        "MeriStationary offers a 14-day return policy for most products, allowing customers to return or exchange items within that period.",
        "Recorded sessions on EduGainer's platform can be accessed by logging into your account and navigating to the class recordings section.",
        "Yes, EduGainer's library accepts book donations, and these contributions are made available to other students in need.",
        "Yes, EduGainer's coaching includes mock interviews for students preparing for college or job applications.",
        "EduGainer's teaches study techniques like time management, active recall, and spaced repetition to enhance learning efficiency.",
        "You can sign up for MeriStationary's newsletter by entering your email on their website to receive updates and offers.",
        "MeriStationary sells both basic and scientific calculators to suit students' various academic needs.",
        "You can check your performance on EduGainer's practice tests by accessing the performance analytics section on your dashboard.",
        "Yes, MeriStationary offers personalized stationery including custom notebooks, pens, and desk organizers.",
        "EduGainer's platform grades online tests using automated systems that provide immediate feedback and score analysis.",
        "EduGainer's live classes cover subjects like mathematics, physics, chemistry, biology, and more for students preparing for exams.",
        "Yes, MeriStationary offers gift-wrapping services for special occasions and during the holiday season.",
        "You can apply for financial aid for EduGainer's coaching by filling out the financial assistance form available on the platform.",  "EduGainer's provides library coaching classes, real-time library seat data, and affordable stationery services through MeriStationary.",
        "EduGainer's allows you to manage library seat bookings in real-time using WebSockets, letting you view and reserve seats easily.",
        "EduGainer's offers coaching in physics, chemistry, mathematics, and other subjects to help students succeed academically.",
        "EduGainer's integrates real-time library management, coaching classes, and affordable stationery services into one comprehensive platform.",
        "You can register for a coaching class by signing up on EduGainer's platform and selecting your preferred subject and time slot.",
        "EduGainer's library services allow real-time seat tracking, convenient booking, and extended hours to ensure productive study sessions.",
        "Yes, EduGainer's provides real-time seat availability using socket.io, allowing students to see vacant spots instantly.",
        "EduGainer's coaching classes use personalized approaches and expert teachers to prepare students thoroughly for their exams.",
        "EduGainer's library services operate from 8 AM to 10 PM, providing students with a comfortable place to study and access resources.",
        "EduGainer's coaching helps alleviate exam stress by offering structured study plans and time management tips tailored to each student.",
        "MeriStationary offers high-quality stationery products, including notebooks, pens, calculators, and other essential supplies.",
        "MeriStationary stands out for its combination of affordability, quality, and a student-focused approach, providing reliable supplies for all.",
        "Yes, MeriStationary ensures affordability for students by offering competitive pricing across all its products.",
        "Yes, MeriStationary provides discounts for bulk purchases, making it ideal for schools and student groups.",
        "MeriStationary provides high-quality products, ensuring durability and reliability, rivaling other popular stationery brands.",
        "Yes, MeriStationary offers scientific calculators along with other study-related tools like geometry sets and rulers.",
        "MeriStationary provides a range of notebooks, including spiral-bound, ruled, and unruled options to suit different needs.",
        "Yes, MeriStationary is committed to sustainability and offers eco-friendly notebooks and paper products.",
        "MeriStationary follows strict quality control standards, ensuring that every product meets the required benchmarks before reaching customers.",
        "Yes, MeriStationary has a hassle-free return policy for products that do not meet customer expectations.",
        "EduGainer's coaching classes can be canceled with a full refund up to 48 hours before the start of the course.",
        "To apply for a bulk discount at MeriStationary, you need to contact customer support with your order details.",
        "Yes, EduGainer's coaching provides special programs to prepare students for college entrance exams such as JEE and NEET.",
        "EduGainer's platform features advanced tools like real-time seat booking, AI-based performance tracking, and interactive study materials.",
        "Yes, you can book library seats for a group of students through EduGainer's seat management tool on the platform.",
        "EduGainer's coaching methods emphasize interactive learning, personalized feedback, and flexible study schedules.",
        "You can request a demo of EduGainer's platform by contacting customer support or filling out the demo request form on the website.",
        "Yes, MeriStationary offers eco-friendly pens made from recycled materials and sustainable packaging.",
        "Yes, EduGainer's provides a one-week free trial for its coaching classes, allowing students to experience the platform.",
        "MeriStationary offers a full refund for unused and undamaged products returned within 14 days of purchase.",
        "EduGainer's delivers personalized learning through AI algorithms that adapt study plans based on each student's performance.",
        "Yes, MeriStationary allows online purchases and delivers products directly to your doorstep with various shipping options.",
        "EduGainer's library offers textbooks, reference materials, previous exam papers, and online resources for comprehensive study support.",
        "EduGainer's coaching classes are scheduled throughout the week, with flexible timings to accommodate students' different schedules.",
        "Yes, EduGainer's provides specially curated study materials designed to help students prepare effectively for competitive exams.",
        "All EduGainer's tutors are certified professionals with years of experience in their respective fields of expertise.",
        "EduGainer's teaches time management techniques, helping students balance study time and other activities efficiently.",
        "To order customized notebooks at MeriStationary, fill out the customization form on the website and specify your preferences.",
        "EduGainer's uses a variety of teaching methods including interactive videos, practice tests, and group discussions to engage students.",
        "Yes, MeriStationary provides international shipping for its products, with additional fees based on the destination country.",
        "EduGainer's ensures student success through personalized feedback, continuous assessments, and expert guidance from tutors.",
        "Yes, EduGainer's has a mobile app available on both Android and iOS, allowing students to access all services on the go.",
        "EduGainer's offers discounts for early sign-ups, group enrollments, and annual subscriptions, providing cost-effective options for students.",
        "Yes, EduGainer's allows long-term library seat bookings, letting students reserve their preferred seats for an entire semester.",
        "EduGainer's accepts payments through credit cards, debit cards, UPI, net banking, and other secure online payment methods.",
        "EduGainer's helps students prepare for board exams by offering targeted study plans, mock exams, and subject-specific coaching.",
        "Yes, EduGainer's offers digital access to its library, where students can browse e-books, online journals, and research papers.",
        "You can cancel your MeriStationary order by logging into your account and selecting the cancel option under order details.",
        "Yes, EduGainer's offers internship opportunities in various departments including content creation, marketing, and operations.",
        "EduGainer's provides online tools such as timed practice exams, detailed feedback, and AI-driven analysis of student performance.",
        "You can contact EduGainer's customer support through the chat feature on the website, email, or by calling the helpline.",
        "MeriStationary offers pre-assembled stationery bundles tailored for students, including notebooks, pens, calculators, and geometry sets.",
        "EduGainer's library seat booking allows a maximum duration of 12 hours per day for each reservation.",
        "EduGainer's tutors undergo a rigorous selection process, ensuring that only highly qualified and experienced individuals are selected.",
        "Yes, MeriStationary offers same-day delivery in select cities for orders placed before noon.",
        "You can renew your library membership on EduGainer's by logging into your account and selecting the renew membership option.",
        "Yes, EduGainer's allows you to change your class schedule by contacting your tutor and selecting an available time slot.",
        "MeriStationary offers a loyalty program where customers can earn points on purchases and redeem them for discounts.",
        "You can see if a seat is reserved in EduGainer's library by checking the seat's status on the platform's seat management tool.",
        "EduGainer's offers online assessments in multiple formats including timed tests, subject-specific quizzes, and comprehensive exams.",
        "Yes, MeriStationary sells a wide variety of art supplies including sketchbooks, colored pencils, and painting materials.",
        "EduGainer's monitors student progress through regular assessments, performance tracking, and periodic feedback sessions.",
        "Yes, MeriStationary offers free shipping on orders above a certain threshold, usually above ₹500.",
        "EduGainer's tutors provide personalized feedback on student assignments, helping them improve their performance continuously.",
        "EduGainer's coaching services offer personalized study plans, expert tutors, and flexible class schedules to help students excel.",
        "Yes, EduGainer's platform provides access to past exam papers from various boards and competitive exams for student practice.",
        "MeriStationary provides standard, express, and same-day shipping options depending on the location and order size.",
        "Yes, EduGainer's offers counseling services for students needing help with career guidance and personal development.",
        "Yes, you can purchase an EduGainer's library membership online by selecting the membership plan and completing the payment process.",
        "Yes, MeriStationary allows customers to exchange products if they receive the wrong item or if it arrives damaged.",
        "EduGainer's conducts exams online using a secure proctoring system, ensuring a fair testing environment for all students.",
        "You can sign up for notifications on EduGainer's platform by going to your profile settings and enabling email or SMS alerts.",
        "MeriStationary's student kit includes notebooks, pens, rulers, erasers, geometry sets, and a scientific calculator.",
        "Yes, EduGainer's offers an installment payment plan for its coaching services, allowing students to pay in flexible monthly installments.",
        "EduGainer's library is equipped with CCTV cameras, fire safety systems, and staff trained in emergency response procedures.",
        "Yes, MeriStationary offers seasonal promotions, especially around the start of the academic year and festive seasons.",
        "EduGainer's displays class availability in real-time on its platform, ensuring students know if a class is full before enrolling.",
        "EduGainer's recommends spiral-bound or A4-sized notebooks for most of its coaching classes, ensuring ample space for notes.",
        "EduGainer's platform provides a detailed performance dashboard where students can track their progress over time.",
        "EduGainer's platform includes secure login features, encrypted data storage, and compliance with industry-standard safety protocols.",
        "MeriStationary recommends ergonomic pens and pencils designed for comfortable writing during long study sessions.",
        "Yes, EduGainer's library offers group study rooms that can be booked for collaborative sessions or group projects.",
        "To become a tutor at EduGainer's, apply through the careers section of the website, and your application will be reviewed by the team.",
        "Yes, MeriStationary allows the use of discount codes during checkout for additional savings on purchases.",
        "EduGainer's supports various types of exams including multiple-choice tests, essay-based exams, and oral assessments.",
        "You can upgrade your EduGainer's subscription plan by logging into your account and selecting the upgrade option under subscriptions.",
        "MeriStationary offers a range of writing pads including spiral, perforated, and legal pads for various writing needs.",
        "Yes, EduGainer's provides topic-specific tutoring, allowing students to focus on areas they need the most help with.",
        "MeriStationary offers a 14-day return policy for most products, allowing customers to return or exchange items within that period.",
        "Recorded sessions on EduGainer's platform can be accessed by logging into your account and navigating to the class recordings section.",
        "Yes, EduGainer's library accepts book donations, and these contributions are made available to other students in need.",
        "Yes, EduGainer's coaching includes mock interviews for students preparing for college or job applications.",
        "EduGainer's teaches study techniques like time management, active recall, and spaced repetition to enhance learning efficiency.",
        "You can sign up for MeriStationary's newsletter by entering your email on their website to receive updates and offers.",
        "MeriStationary sells both basic and scientific calculators to suit students' various academic needs.",
        "You can check your performance on EduGainer's practice tests by accessing the performance analytics section on your dashboard.",
        "Yes, MeriStationary offers personalized stationery including custom notebooks, pens, and desk organizers.",
        "EduGainer's platform grades online tests using automated systems that provide immediate feedback and score analysis.",
        "EduGainer's live classes cover subjects like mathematics, physics, chemistry, biology, and more for students preparing for exams.",
        "Yes, MeriStationary offers gift-wrapping services for special occasions and during the holiday season.",
        "You can apply for financial aid for EduGainer's coaching by filling out the financial assistance form available on the platform."
    ]
}

# Creating DataFrame
expanded_df = pd.DataFrame(expanded_data)

# Saving to CSV
expanded_csv_file_path = "expanded_finetuning_google_gmein_50_lines.csv"
expanded_df.to_csv(expanded_csv_file_path, index=False)

# Output the file path
print(expanded_csv_file_path)
