name: Monthly Task Scheduler

on:
  schedule:
    # Runs on the first day of every month at 00:00 UTC
    - cron: '20 9 * * 1'

jobs:
  monthly-task:
    name: Execute Monthly Tasks
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16' # Specify the Node.js version as per your project

    - name: Install Dependencies
      run: npm install
      working-directory: ./Backend

    - name: Execute Monthly Task
      run: node cronJobs.js
      working-directory: ./Backend

    - name: Send Email Notification
      env:
        EMAIL: ${{ secrets.EMAIL }}
        PASSWORD: ${{ secrets.PASSWORD }}
      run: node emailSender.js
      working-directory: ./Backend
