name: Monthly Task Scheduler
on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  monthly-task:
    name: Execute Monthly Tasks
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '16'

    - name: Install Dependencies
      run: |
        cd Backend
        npm install
        echo "Dependencies installed successfully"
        npm list

    - name: Execute Monthly Task
      env:
        MONGODB_URI: ${{ secrets.MONGODB_URI }}
        NODE_ENV: development
      run: |
        cd Backend
        node cronJobs.js

    - name: Upload logs
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: execution-logs
        path: Backend/logs